version: '3.8'

services:
  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ingredient

  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"

#  ingredientservice:
#    image: ghcr.io/thi-cnd/ingredient_service:latest
#    platform: linux/amd64
#    restart: unless-stopped
#    ports:
#      - "8080:8080"
#    environment:
#      DB_URL: jdbc:postgresql://postgres:5432/ingredient
#      DB_USER: postgres
#      DB_PASSWORD: password
#      RABBIT_HOST: rabbitmq
#      RABBIT_PORT: 5672
#      RABBIT_USER: guest
#      RABBIT_PASSWORD: guest
#    depends_on:
#      - postgres
#      - rabbitmq