version: '3.8'

services:
  ingredientsservice:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: ingredientsservice
    depends_on:
      - db
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/$DB_DATABASE
      - SPRING_DATASOURCE_USERNAME=$DB_USER
      - SPRING_DATASOURCE_PASSWORD=$DB_PASSWORD
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_DATABASE
    ports:
      - "$LOCAL_PORT:$DOCKER_PORT"